// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var add, get, set, _currentSocketName, _sockets;
    _currentSocketName = null;
    _sockets = [];
    add = function(name, socket) {
      return _sockets.push({
        name: name,
        socket: socket
      });
    };
    set = function(name) {
      return _currentSocketName = name;
    };
    get = function(name) {
      var s;
      if (name == null) {
        name = _currentSocketName;
      }
      s = _sockets.filter(function(p) {
        return p.name === name;
      })[0];
      return s.socket;
    };
    return {
      get: get,
      set: set,
      add: add
    };
  });

}).call(this);
