// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var Root;
    Root = (function() {

      function Root() {}

      Root.vm = null;

      return Root;

    })();
    return {
      Root: Root
    };
  });

}).call(this);
