// Generated by CoffeeScript 1.3.3
(function() {

  define(["Ural/Modules/pubSub"], function(pubSub) {
    var Root, User;
    User = (function() {

      function User() {
        var name;
        name = ko.observable(name);
      }

      return User;

    })();
    Root = (function() {

      function Root() {
        this.user = ko.observable();
        this.vm = null;
      }

      Root.prototype._loginPopup = function(returnRoute, returnExec) {
        var returnUrl;
        returnUrl = "#" + returnRoute + "/!/user/$user";
        if (returnExec) {
          returnUrl += "/!/" + returnExec;
        }
        returnUrl = escape(returnUrl);
        return _u.popup("/Account/OAuth?serviceName=Twitter&extWindow=true&returnUrl=" + returnUrl, 600, 400);
      };

      Root.prototype.login = function(returnRoute, returnExec) {};

      Root.prototype.logoff = function(href) {
        var _this = this;
        return $.get(href, function() {
          return _this.user(null);
        });
      };

      return Root;

    })();
    return {
      Root: Root
    };
  });

}).call(this);
