// Generated by CoffeeScript 1.3.3
(function() {

  define(["Ural/Modules/pubSub"], function(pubSub) {
    var State;
    State = (function() {

      function State() {
        var _this = this;
        this.isLoading = ko.observable(false);
        this.isPageMove = ko.observable(false);
        this.loadingStarts = ko.observable();
        this.isEmptyResult = ko.observable(false);
        this.isNotEmptyResult = ko.computed(function() {
          return !_this.isEmptyResult();
        });
        this.isFiltering = ko.computed(function() {
          return _this.isLoading() && !_this.isPageMove();
        });
        this.state = ko.observable("modifyed");
        pubSub.subOnce("model", "list_changed", "state", function(data) {
          if (data.changeType === "update_begin") {
            return _this.state("updating");
          } else {
            return _this.state("modifyed");
          }
        });
      }

      return State;

    })();
    return {
      State: State
    };
  });

}).call(this);
