// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var messages;
    messages = {
      update_success: "Сохранение успешно",
      update_fail: "Ошибка сохранения",
      validation_error: "Ошибка валидации",
      nothing_to_commit: "Изменений не обнаружено"
    };
    return {
      messages: messages
    };
  });

}).call(this);
