// Generated by CoffeeScript 1.3.3
(function() {

  define(["Ural/Modules/pubSub"], function(pubSub) {
    return ko.bindingHandlers.link = {
      init: function(element, valueAccessor, allBindingsAccessor, viewModel) {
        var href;
        href = $(element).attr("href");
        $(element).bind("click", function(e) {
          e.preventDefault();
          href = href.replace(/^\/?#\/?/, "");
          return pubSub.pub("href", "change", {
            href: href
          });
        });
        return ko.utils.domNodeDisposal.addDisposeCallback(element, function() {
          return $(element).unbind("click");
        });
      }
    };
  });

}).call(this);
