// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    return ko.bindingHandlers.loading = {
      init: function(element, valueAccessor, allBindingsAccessor, viewModel) {
        return $(element).hide();
      },
      update: function(element, valueAccessor, allBindingsAccessor, viewModel) {
        var bindingOpts, toggleLayout, value;
        bindingOpts = allBindingsAccessor().loadingOpts;
        toggleLayout = bindingOpts.toggleLayout;
        value = ko.utils.unwrapObservable(valueAccessor());
        if (value) {
          $("#" + toggleLayout).hide();
          return $(element).show();
        } else {
          $(element).hide();
          return $("#" + toggleLayout).show();
        }
      }
    };
  });

}).call(this);
