// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var ini;
    ini = function() {
      return ko.bindingHandlers.mval = {
        init: function(element, valueAccessor, allBindingsAccessor, viewModel) {
          var mask, num, opts;
          opts = allBindingsAccessor().mvalOpts;
          mask = new RegExp("^(" + opts.mask + ")$");
          num = opts.num;
          return ko.utils.registerEventHandler(element, "change", function() {
            var observable, val;
            observable = valueAccessor();
            val = $(element).val().trim();
            if (mask.test(val)) {
              if (num) {
                val = parseInt(val);
              }
              return observable(val);
            } else {
              return $(element).val(observable());
            }
          });
        },
        update: function(element, valueAccessor) {
          var val;
          val = ko.utils.unwrapObservable(valueAccessor());
          return $(element).val(val);
        }
      };
    };
    return {
      ini: ini
    };
  });

}).call(this);
