// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var ini;
    ini = function() {
      return ko.bindingHandlers.popover = {
        init: function(element, valueAccessor, allBindingsAccessor, viewModel) {
          var opts, placement, popoverOpts, template, title, val;
          if (typeof valueAccessor() === 'string') {
            val = valueAccessor();
            if (val.indexOf("#" === 0)) {
              template = $(val)[0].outerHTML;
              val = $(val + " .popover-content").html();
            }
          } else {
            val = ko.utils.unwrapObservable(valueAccessor());
          }
          opts = allBindingsAccessor();
          if (opts) {
            opts = opts.popoverOpts;
          }
          if (opts) {
            if (opts.title) {
              title = opts.title;
            }
            if (opts.placement) {
              placement = opts.placement;
            }
            if (opts.template) {
              template = $("#" + opts.template)[0].outerHTML;
            }
          }
          if (placement == null) {
            placement = "top";
          }
          popoverOpts = {
            content: val,
            placement: placement
          };
          popoverOpts.title = title ? title : "";
          if (template) {
            popoverOpts.template = template;
          }
          $(element).popover(popoverOpts);
          $(element).bind("click", function(e) {
            return e.preventDefault();
          });
          return ko.utils.domNodeDisposal.addDisposeCallback(element, function() {
            $(element).popover("hide");
            return $(element).triggerHandler("destroyed");
          });
        }
      };
    };
    return {
      ini: ini
    };
  });

}).call(this);
