// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var ini;
    ini = function() {
      return ko.bindingHandlers.slider = {
        init: function(element, valueAccessor, allBindingsAccessor, viewModel) {
          var max, min, opts, val, valAccessor;
          opts = allBindingsAccessor().sliderOpts;
          valAccessor = valueAccessor();
          val = ko.utils.unwrapObservable(valAccessor);
          if (opts) {
            min = opts.min;
          }
          if (opts) {
            max = opts.max;
          }
          if (min == null) {
            min = 0;
          }
          if (max == null) {
            max = 100;
          }
          return $(element).slider({
            range: true,
            min: min,
            max: max,
            values: [val.from(), val.to()],
            slide: function(event, ui) {
              val.from(ui.values[0]);
              return val.to(ui.values[1]);
            }
          });
        },
        update: function(element, valueAccessor, allBindingsAccessor, viewModel) {
          var val, valAccessor;
          valAccessor = valueAccessor();
          val = ko.utils.unwrapObservable(valAccessor);
          $(element).slider("values", 0, val.from());
          return $(element).slider("values", 1, val.to());
        }
      };
    };
    return {
      ini: ini
    };
  });

}).call(this);
