// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var ini;
    ini = function() {
      return ko.bindingHandlers.tooltip = {
        init: function(element, valueAccessor, allBindingsAccessor, viewModel) {
          var val;
          val = ko.utils.unwrapObservable(valueAccessor());
          $(element).tooltip({
            title: val
          });
          $(element).bind("click", function(e) {
            return e.preventDefault();
          });
          return ko.utils.domNodeDisposal.addDisposeCallback(element, function() {
            $(element).tooltip("hide");
            return $(element).triggerHandler("destroyed");
          });
        }
      };
    };
    return {
      ini: ini
    };
  });

}).call(this);
