// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var ini;
    ini = function() {
      return ko.bindingHandlers.val = {
        init: function(element, valueAccessor, allBindingsAccessor, viewModel) {
          var val;
          val = ko.utils.unwrapObservable(valueAccessor());
          $(element).val(parseInt(val));
          return $(element).change(function() {
            val = $(element).val();
            if (typeof val === "string") {
              val = parseInt(val);
            }
            return valueAccessor()(val);
          });
        },
        update: function(element, valueAccessor) {
          var val;
          val = ko.utils.unwrapObservable(valueAccessor());
          return $(element).val(val);
        }
      };
    };
    return {
      ini: ini
    };
  });

}).call(this);
