// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var ini;
    ini = function(lang, onDone) {
      return require(["Ural/i18n/" + lang + "/messages"], function(msg) {
        return onDone({
          messages: msg.messages
        });
      });
    };
    return {
      ini: ini
    };
  });

}).call(this);
