// Generated by CoffeeScript 1.3.3
(function() {

  define(["Ural/Libs/socket.io/socket.io.min.js"], function() {
    var Socket;
    Socket = (function() {

      function Socket(url) {
        this.url = url;
        this.channels = [];
      }

      Socket.prototype._createChannel = function(name) {
        return io.connect("" + this.url + "/" + name);
      };

      Socket.prototype._getChannel = function(name) {
        var channel, cn;
        cn = this.channels.filter(function(c) {
          return c.name === name;
        })[0];
        if (!cn) {
          channel = this._createChannel(name);
          cn = {
            name: name,
            channel: channel
          };
          this.channels.push(cn);
        }
        return cn.channel;
      };

      Socket.prototype.sub = function(channel, event, onData) {
        return this._getChannel(channel).on(event, onData);
      };

      Socket.prototype.pub = function(channel, event, data) {
        return this._getChannel(channel).emit(event, data);
      };

      return Socket;

    })();
    return {
      Socket: Socket
    };
  });

}).call(this);
