// Generated by CoffeeScript 1.3.3
(function() {

  define(["http://js.pusher.com/1.11/pusher.min.js"], function() {
    var PusherSocket;
    PusherSocket = (function() {

      function PusherSocket(key) {
        this.pusher = new Pusher(key);
        this.channels = [];
      }

      PusherSocket.prototype.sub = function(channelName, event, onRec) {
        var channel;
        channel = this.pusher.subscribe(channelName);
        channel.bind(event, onRec);
        return this.channels[channelName + "." + event] = {
          channel: channel,
          callback: onRec
        };
      };

      PusherSocket.prototype.unsub = function(channelName, event) {
        var s;
        s = this.channels[channelName + "." + event];
        return s.channel.unbind(event, s.callback);
      };

      return PusherSocket;

    })();
    return {
      Socket: PusherSocket
    };
  });

}).call(this);
