// Generated by CoffeeScript 1.3.3
(function() {

  define(["order!Ural/Libs/signalr/jquery.signalR-0.5.0.min.js", "order!/signalr/hubs", "Ural/Libs/jquery.cookie"], function() {
    var Socket;
    Socket = (function() {

      function Socket(url) {
        this.url = url;
        this._channels = [];
      }

      Socket.prototype._createChannel = function(name) {
        return $.connection[name];
      };

      Socket.prototype._getChannel = function(name) {
        var channel, cn,
          _this = this;
        cn = this._channels.filter(function(c) {
          return c.name === name;
        })[0];
        if (!cn) {
          channel = this._createChannel(name);
          cn = {
            name: name,
            channel: channel
          };
          if (this._channels.length === 0) {
            $.connection.hub.start().done(function() {
              _this.userId = $.connection.hub.id;
              return $.cookie("SIGNALR_ID", _this.userId, {
                path: "/"
              });
            });
          }
          this._channels.push(cn);
        }
        return cn.channel;
      };

      Socket.prototype._getUserId = function() {
        return $.cookie("SIGNALR_ID");
      };

      Socket.prototype.sub = function(channel, event, onData) {
        var _this = this;
        return this._getChannel(channel)[event] = function(data) {
          if (!data._userId || _this._getUserId() !== data._userId) {
            return onData(data);
          }
        };
      };

      Socket.prototype.pub = function(channel, event, data) {
        return this._getChannel[channel][event](data);
      };

      return Socket;

    })();
    return {
      Socket: Socket
    };
  });

}).call(this);
