// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var OrderByList;
    OrderByList = (function() {

      function OrderByList(opts, selectedKey) {
        var t, _i, _len,
          _this = this;
        this.opts = ko.observableArray();
        if (opts) {
          for (_i = 0, _len = opts.length; _i < _len; _i++) {
            t = opts[_i];
            this.opts.push(t);
          }
        }
        this.selectedOpt = ko.observable();
        if (selectedKey) {
          this.select(selectedKey);
        }
        this.expr = ko.computed(function() {
          if (_this.selectedOpt()) {
            return _this.selectedOpt().key;
          }
        });
      }

      OrderByList.prototype.select = function(key) {
        return this.selectedOpt(this.opts().filter(function(f) {
          return f.key === key;
        })[0]);
      };

      OrderByList.prototype.serialize = function() {
        return {
          key: this.selectedOpt().key
        };
      };

      OrderByList.prototype.deserialize = function(obj) {
        if (obj.key) {
          return this.select(obj.key);
        }
      };

      return OrderByList;

    })();
    return {
      OrderByList: OrderByList
    };
  });

}).call(this);
